### ISSUE TITLE
Expand README

### ISSUE THREAD

**Issue by tobyhodges** [tobyhodges/cuddly-waffle#1]
We should update and expand the README, in line with [the recommendations we make in Collaborative Lesson Development Training](https://carpentries.github.io/lesson-development-training/collaborating-newcomers.html#readme). We should include some or all of the following:

- lesson title
- lesson description
- link to the rendered version of the lesson
- contact information for the Maintainers
- contributing information
- credits/acknowledgements
- citation info
- a brief mention of the CC-BY license, with a link to the license file.

**Comment by anenadic** [comment]
I am going to have a look into this today @tobyhodges.
